In [2]:
#import numpy library
import numpy as np

In [6]:
#making an array
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
#checking type
type(a)

numpy.ndarray

In [8]:
#checking length of an array
len(a)

8

In [9]:
#creating array with zeros function
b = np.zeros(4)
b

array([0., 0., 0., 0.])

In [11]:
#creating array with ones function
c = np.ones(3)
c

array([1., 1., 1.])

In [13]:
#creating array with empty function
x = np.empty(4)
x

array([2.12199579e-314, 1.44635488e-307, 3.43869690e-321, 8.21212371e-312])

In [14]:
#creating array with range of elements
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
#creating array with specific range of elements
x = np.arange(3,8)
x

array([3, 4, 5, 6, 7])

In [16]:
#continue
x = np.arange(2,20,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#creating array with linearly space
c = np.linspace(2,20,num=14)
c

array([ 2.        ,  3.38461538,  4.76923077,  6.15384615,  7.53846154,
        8.92307692, 10.30769231, 11.69230769, 13.07692308, 14.46153846,
       15.84615385, 17.23076923, 18.61538462, 20.        ])

In [23]:
#specific data type in array
x = np.ones(6,dtype=np.int8)
x

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [24]:
#specific data type in array
c = np.ones(8,dtype=np.float64)
c

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
#creating 2D array
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [30]:
#creating 2D array with zeros function
a = np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
#creating 2D array with ones function
a = np.ones((4,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
#creating 2D array with empty function
a = np.empty((2,2))
a

array([[2.12199579e-314, 1.44635488e-307],
       [3.43869690e-321, 8.21212371e-312]])

In [37]:
#3D array
a = np.arange(16).reshape(2,2,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

# Numpy Practice Seassion

In [1]:
#import numpy library
import numpy as np

In [2]:
food = np.array(["samos","pakora","raita"])
food

array(['samos', 'pakora', 'raita'], dtype='<U6')

In [3]:
prices = np.array([5,5,5])
prices

array([5, 5, 5])

In [4]:
type(prices)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(prices)

3

In [7]:
len(food)

3

In [10]:
a = np.ones(6, dtype=np.int64)
a

array([1, 1, 1, 1, 1, 1], dtype=int64)

In [12]:
b = np.zeros(5, dtype=np.int64)
b

array([0, 0, 0, 0, 0], dtype=int64)

In [13]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
d = np.arange(1,11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
e = np.arange(5,55,5)
e

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
f = np.linspace(5,50,num=10,dtype=np.int64)
f

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50], dtype=int64)

## Array Functions

In [20]:
#sorting
a = np.array([5,3,6,2,4,3,1,8,7])
a.sort()
a

array([1, 2, 3, 3, 4, 5, 6, 7, 8])

In [21]:
b = np.array([11,10,14,13,12,16,15])
b

array([11, 10, 14, 13, 12, 16, 15])

In [22]:
#concatinate
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8, 11, 10, 14, 13, 12, 16, 15])

In [23]:
c.sort()
c

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16])

In [24]:
#2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
a.ndim

2

In [26]:
#3D Array

a = np.array([[[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]],
            [[13,14,15],[16,17,18]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [27]:
a.ndim

3

In [29]:
#convert 1D arrray into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#row wise
b = a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
b.ndim

2

In [32]:
#column wise
b = a[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# NUMPY PRACTICE

In [1]:
#import numpy library
import numpy as np

In [3]:
# creating 1 D array
a = np.array([1,3,4,56,7,8])
a

array([ 1,  3,  4, 56,  7,  8])

In [4]:
#checking type 
type(a)

numpy.ndarray

In [5]:
#checking length
len(a)

6

In [9]:
#creating array using zeros function
a = np.zeros(5, dtype=np.int64)
a

array([0, 0, 0, 0, 0], dtype=int64)

In [10]:
#creating array using ones function
b = np.ones(6,dtype=np.int64)
b

array([1, 1, 1, 1, 1, 1], dtype=int64)

In [14]:
#creating array using empty function
np.empty(7,dtype=np.float32)

array([0.0000e+00, 1.4013e-45, 0.0000e+00, 6.9796e-39, 1.1210e-42,
       0.0000e+00, 1.0762e-42], dtype=float32)

In [15]:
#creating array with range of elements
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [16]:
#creating array with range of elements
np.arange(6,20)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
#creating array with range of elements
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
#creating array with linerly space function
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
#creating 2D array
c = np.array([[1,2,3,11],[4,5,6,12],[7,8,9,13]])
c

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [22]:
#creating 2D array with ones function
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
#creating 2D array with zeros function
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
#creating 2D array with empty function
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
#creating 3D array
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

# Array Function Practice